spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafios
    username: postgres
    password: 107400Ch
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema:task
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migration: true
    locations: classpath:db/migration
    schemas: task